[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"
[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/sessions"
[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"
[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"
[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"
[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
[prune]
  go-tests = true
  unused-packages = true